### PR TITLE
Fix arbitrary border color value being merged incorrectly

### LINKED ISSUE #193: Arbitrary properties should not be overridden when a type is specified
When I use this class string: `border-b border-[color:rgb(var(--color-gray-500-rgb)/50%))]` 

`border-[color:rgb(var(--color-gray-500-rgb)/50%))]` overrides `border-b`

I think it could be really useful to detect when a type is defined on an arbitrary property and override it accordingly (or don't when not).

In this case, `border-[color:`… should not override `border-b`

### PR DESCRIPTION
**Pull request by dcastil**
Closes #193

### CODE REVIEW

File: src/lib/validators.ts [hunk 1]
```diff
@@ -81,11 +57,47 @@ export function isTshirtSize(classPart: string) {
...
+function isValueLength(value: string) {
+    return lengthUnitRegex.test(value)
+}
+
+function isValueNever() {
+    return false
+}
+
+function isValueUrl(value: string) {
+    return value.startsWith('url(')
```
Comment (gjtorikian) [inline src/lib/validators.ts:90]: This is missing `value.startsWith('url:')` which was previously present -- is that intentional ?

Comment (gjtorikian) [reply src/lib/validators.ts:90]: Actually, I guess all the colons are dropped, due to the regex change -- ignore me!

Comment (dcastil) [reply src/lib/validators.ts:90]: Yeah I check for the label in the second argument to `getIsArbitraryValue()`, the `isValueUrl` only needs to check the non-label part of the arbitrary value.
